---
name: Flake Finder

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  e2e:
    name: E2E Consuming Projects
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ['admiral', 'submariner', 'submariner-operator', 'lighthouse']
        deploytool: ['operator', 'helm']
        globalnet: ['', 'globalnet']
        lighthouse: ['', 'lighthouse']
        cable_driver: ['', 'wireguard', 'libreswan']
        exclude:
          # No need to specify using=lighthouse in Lighthouse repo
          - project: lighthouse
            lighthouse: lighthouse
          # It doesn't make sense to run Helm tests in the operator repo
          - project: submariner-operator
            deploytool: helm
          # Our Helm setup doesn’t know how to deploy other cable drivers
          - deploytool: helm
            cable_driver: wireguard
          - deploytool: helm
            cable_driver: libreswan
    steps:
      - name: Check out the Shipyard repository
        uses: actions/checkout@v2

      - name: Reclaim free space!
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          free -h

      - name: Build the latest Shipyard image
        run: make images

      - name: Check out the ${{ matrix.project }} repository
        uses: actions/checkout@v2
        with:
          repository: submariner-io/${{ matrix.project }}

      - name: Make sure ${{ matrix.project }} is using the built Shipyard image
        run: sed -i 's/shipyard-dapper-base:*.*/shipyard-dapper-base:dev/' Dockerfile.dapper

      - name: Run E2E deployment and tests
        run: make e2e using="${{ matrix.deploytool }} ${{ matrix.globalnet }} ${{ matrix.lighthouse }} ${{ matrix.cable_driver }}"

      - name: Post mortem
        if: failure()
        run: |
          df -h
          free -h
          make post-mortem
